<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>ECMAScript 2017 Language Specification asdadadadadasdasd d哈的客户阿萨的良好</title>
</head>
<body>
  <script>
    /* 
      一种新的代码思路：callback可以直接传函数 但是需要注意参数的对应位置和个数 否则可能会出错
      async函数：使得异步操作变得更加方便，是Generator函数的语法糖。将Generator函数的星号(*)替换成async，将yield替换成await
      async函数对Generator函数的改进：
      1.内置执行器:Generator函数的执行必须依靠执行器 所以才有了co模块 而async函数自带执行器 async函数的执行和普通函数一样
      2.更好的语义：async 异步操作 await等待结果
      3.更广的适用性：co模块约定 yield命令后面只能是Thunk函数或Promise对象 而async函数的await命令后面 可以是Promise对象和原始类型的值(数值、字符串和
      布尔值 但这时会自动转成立即resolved的Promise对象)
      4.返回值是Promise
      基本语法：返回一个Promise对象 可以使用then方法添加回调函数 等await返回结果 再接着执行函数体后面的语句
      async function getStockPriceByName(name) {
       const symbol = await getStockSymbol(name);
       const stockPrice = await getStockPrice(symbol);
      return stockPrice;
     }
     getStockPriceByName('goog').then(res => console.log(res))
     function timeout(ms) {
       return new Promise(resolve => setTimeout(resolve, ms));
     }
     async function asyncPrint(value, ms) {
       await timeout(ms);
       console.log(value);
     }
     asyncPrint('hello world', 5000);
     async:函数有多种使用形式
     语法：async函数返回一个Promise对象，函数内部return语句返回的值 会成为then方法回调函数的参数
     async function f() {
       return 'callback arguments';
     }
     f().then(data => console.log(data))
     async函数内部抛出错误 会导致返回的Promise对象变成reject状态 抛出的错误对象会被catch方法回调函数接收到
     async function test() {
       throw new Error('callback error arg');
     }
     test().then((e, v) => {
       console.log(e)
       console.log(v)
     })
     Promise对象的状态变化：async函数返回的Promise对象 必须等到内部所以await命令后面的Promise对象执行完 才会发生状态变化
     除非遇到retuen语句或者抛出错误。也就是说只要async函数内部的异步操作执行完 才会执行then方法指定的回调函数
     async function getTitle(url) {
       return 'test'
      //  let response = await fetch(url), html = await response.text();
      //  return html.match(/<title>([\s\S]+)<\/title>/i)[1]
     }
     getTitle().then(console.log)
     await命令：正常情况下 await命令后面是一个Promise对象 返回该对象的结果 如果不是Promise对象 就直接返回相应的值
     async function f() {
       return await 123;
     }
     f().then(console.log)
     注：如果await命令后面是一个thenable对象(即定义then方法的对象)，那么await会将其等同于Promise对象
     class Sleep {
       constructor(timeout) {
         this.timeout = timeout;
       }
       then(resolve, reject) {
         const startTime = Date.now();
         setTimeout(() => resolve(1222), this.timeout)
       }
     }
     (async () => {
       const sleepTime = await new Sleep(1000)
       console.log(sleepTime);
     })();
     function sleep(interval) {
       return new Promise(resolve => setTimeout(resolve, interval))
     }
     async function one2FiveInAsync() {
       for(let i = 1; i <= 5; i++) {
         console.log(i);
         await sleep(1000);
       }
     }
    one2FiveInAsync()
    注：如果await命令后面的Promise对象如果变成reject状态 则reject的参数会被catch方法的回调函数接收到
    async function f() {
       await Promise.reject('出错了');
     }
     f().then().catch(err => console.log(err))
     任何一个await语句后面的Promise对象变为reject状态 那么整个async函数都会中断执行
     也就是说捕获异常必须再async内部完成
     有时 我们希望即使前一个异步操作失败 也不要中断后面的异步操作 这时可以将第一个await放在try...catch结构里面
     不管这个异步操作是否成功 第二个await都会执行
     async function f() {
      // await Promise.reject('出错了');
       try {
         await Promise.reject('出错了');
       }
      //  内部已经捕获到了错误
       catch(e) {}
       return await Promise.resolve('hello world');
     }
     f().then(console.log, console.log)
     另一种方法是await后面的Promise对象再跟一个catch方法 处理前面可能出现的错误
     async function f() {
       await Promise.reject('出错了').catch(console.log)
       return await Promise.resolve('hello world');
     }
     f().then(console.log)
     错误处理：防止出错的方法 也是将其放在try....catch代码块之中
     使用注意点：
      1.因为Promise对象的运行结果 可能是rejected 所以最好把await命令放在try...catch代码块中
      2.多个await命令后面的异步操作 如果不存在继发关系 最好让它们同时触发 这样就会缩短程序的执行时间
        let [foo, bar] = await Promise.all([getFoo(), getBar()]) // 同时触发
        // 或者
        let fooPromise = getFoo(), barPromise = getBar(), foo = await fooPromise(), bar = await barPromise()
      3.await只能在async函数之中 否则会报错，forEach的回调是并发执行的，如果确实希望多个请求并发执行 可以使用Promise.all方法
        async function dbFuc(db) {
       let docs = [{}, {}, {}];
       let promises = docs.map(doc => db.post(doc));
       // 第一种 
       // let results = await Promise.all(promises);
       //  第二种
       let results = [];
       for(let promise of promises) {
         results.push(await promise());
       }
       console.log(results);
     }
     4.async函数可以保留运行堆栈,
     b运行得时候 a是暂停执行 上下文环境都保存着 一旦b或c报错 错误堆栈将包括a
     const a = async () => {
       await b();
       c();
     }
     async函数的实现原理：就是将Generator函数和自动执行器 包装在一个函数里
     仔细思考下：什么是异步操作 就是分为两个阶段 第一阶段就是先执行 然后再去做别的事情 等结果返回之后 再去执行接下来的事情
     function fn(args) {
       return spawn(function *() {})
     }
     function spawn(genF) {
       return new Promise((resolve, reject) => {
         const gen = genF();
         function step(nextF) {
           let next;
           try {
             next = nextF();
           } catch(e) {
             return reject(e);
           }
           if (next.done) {
             return resolve(next.value);
           }
           Promise.resolve(next.value).then(v => {
             step(function() { return gen.next(v) })
           }, e => {
             step(function() { return gen.throw(e) })
           })
         }
         step(function() { return gen.next(undefined) });
       })
     }
     6：按顺序完成异步操作: 继发 并发！！！
     function logInOrder(urls) {
      //  参数是url里面的text文档的promise对象数组
       const textPromises = urls.map(url => fetch(url).then(res => res.text()))
       textPromises.reduce((chain, textPromise) =>chain.then(() => textPromise).then(res => console.log(res)), Promise.resolve())
     }
     // 最外面是个异步的
     async function logInOrder(urls) {
        //  外面依然是并发的
       const textPromises = urls.map(async url => {
        //  里面也是个继发的
        const response = await fetch(url);
        return response.text();
       });
       for(const textPromise of textPromises) {
         console.log(await textPromise)
       }
     }
     logInOrder(['http://192.168.0.126:8888/', 'http://192.168.0.126:8881/'])
     7:顶层await: 有一个语法提案 允许在模块的顶层独立使用await 这个提案的目的 是借用await解决模块异步加载的问题
     await的一些使用场景:
      1.import方法加载
    注意 如果加载多个包含顶层await命令的模块 加载命令是同步执行的
    */
    
  </script>
</body>
</html>